### ISSUE TITLE
Make the bot cluster aware

### ISSUE THREAD

**Issue by bruntonspall** [bruntonspall/xgovslackbot#30]
The bot is deployed to a CloudFoundry based PaaS, which can dynamically create or destroy nodes as part of the self healing fabric.

The bot should be mostly unware of what the platform is doing.

for some reason, when there are multiple instances running, it looks like all of the instances get the messages from slacks API, and responds, creating multiple responses to the end user.

Work out what is going on, and how to ensure that either incoming messages are load balanced between instances, or how to ensure only one response is sent per incoming request.

**Comment by rboulton** [comment]
This is now resolved, by #36 (but I don't have permission to close this issue)
