### ISSUE TITLE
Notify new users about the username convention.

### ISSUE THREAD

**Issue by edwardhorsford** [bruntonspall/xgovslackbot#6]
I send many new users a DM telling them about our username convention and pointing to where they can change it.

Perhaps the bot can help with setting the name / else tell new users the convention?

The existing text I use is:
```
Hello <name>,
Can you please add your organisation name to the end of your slack handle? For example, `username_hmrc` or _`username_dwp`
You can change it here: https://<slackorg>/account/settings#username
```

**Comment by alextea** [comment]
Would be good if it could ask if they could add their role and dept to their profile too.

**Comment by pgchamberlin** [comment]
I've created a PR (#7) which adds the basics of this functionality: the bot DMs the user when they join. The message needs work though - I've just put in some placeholder text.

**Comment by edwardhorsford** [comment]
I think this line of text is now incorrect. We need people to change their display name from here: https://ukgovernmentdigital.slack.com/account/profile#display_name_profile_field

Annoyingly you can't direct link to the edit field as far as I could see.

**Comment by pgchamberlin** [comment]
Good point. This PR should sort it hopefully: https://github.com/bruntonspall/xgovslackbot/pull/8
